// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksAPI.Models;

namespace ParksAPI.Migrations
{
    [DbContext(typeof(ParksAPIContext))]
    [Migration("20200821164739_RemoveCamping")]
    partial class RemoveCamping
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksAPI.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("State");

                    b.Property<string>("Type");

                    b.Property<string>("Website");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Name = "Crater Lake National Park",
                            State = "Oregon",
                            Type = "national",
                            Website = "https://www.nps.gov/crla/index.htm"
                        },
                        new
                        {
                            ParkId = 2,
                            Name = "Mount Rainier National Park",
                            State = "Washington",
                            Type = "national",
                            Website = "https://www.nps.gov/mora/index.htm"
                        },
                        new
                        {
                            ParkId = 3,
                            Name = "North Cascades National Park",
                            State = "Washington",
                            Type = "national",
                            Website = "https://www.nps.gov/noca/index.htm"
                        },
                        new
                        {
                            ParkId = 4,
                            Name = "Olymic National Park",
                            State = "Washington",
                            Type = "national",
                            Website = "https://www.nps.gov/olym/index.htm"
                        },
                        new
                        {
                            ParkId = 5,
                            Name = "Yellowstone National Park",
                            State = "Wyoming",
                            Type = "national",
                            Website = "https://www.nps.gov/yell/index.htm"
                        },
                        new
                        {
                            ParkId = 6,
                            Name = "Grand Teton National Park",
                            State = "Wyoming",
                            Type = "national",
                            Website = "https://www.nps.gov/grte/index.htm"
                        },
                        new
                        {
                            ParkId = 7,
                            Name = "Glacier National Park",
                            State = "Montana",
                            Type = "national",
                            Website = "https://www.nps.gov/glac/index.htm"
                        },
                        new
                        {
                            ParkId = 8,
                            Name = "Channel Islands National Park",
                            State = "California",
                            Type = "national",
                            Website = "https://www.nps.gov/glac/index.htm"
                        },
                        new
                        {
                            ParkId = 9,
                            Name = "Death Valley National Park",
                            State = "California",
                            Type = "national",
                            Website = "https://www.nps.gov/deva/index.htm"
                        },
                        new
                        {
                            ParkId = 10,
                            Name = "Joshua Tree National Park",
                            State = "California",
                            Type = "national",
                            Website = "https://www.nps.gov/jotr/index.htm"
                        },
                        new
                        {
                            ParkId = 11,
                            Name = "Lassen Volcanic National Park",
                            State = "California",
                            Type = "national",
                            Website = "https://www.nps.gov/lavo/index.htm"
                        },
                        new
                        {
                            ParkId = 12,
                            Name = "Pinnacles National Park",
                            State = "California",
                            Type = "national",
                            Website = "https://www.nps.gov/pinn/index.htm"
                        },
                        new
                        {
                            ParkId = 13,
                            Name = "Redwood National Park",
                            State = "California",
                            Type = "national",
                            Website = "https://www.nps.gov/redw/index.htm"
                        },
                        new
                        {
                            ParkId = 14,
                            Name = "Sequoia and King's Canyon National Park",
                            State = "California",
                            Type = "national",
                            Website = "https://www.nps.gov/seki/index.htm"
                        },
                        new
                        {
                            ParkId = 15,
                            Name = "Yosemite National Park",
                            State = "California",
                            Type = "national",
                            Website = "https://www.nps.gov/yose/index.htm"
                        },
                        new
                        {
                            ParkId = 16,
                            Name = "Great Basin National Park",
                            State = "Nevada",
                            Type = "national",
                            Website = "https://www.nps.gov/grba/index.htm"
                        },
                        new
                        {
                            ParkId = 17,
                            Name = "Arches National Park",
                            State = "Utah",
                            Type = "national",
                            Website = "https://www.nps.gov/arch/index.htm"
                        },
                        new
                        {
                            ParkId = 18,
                            Name = "Bryce Canyon National Park",
                            State = "Utah",
                            Type = "national",
                            Website = "https://www.nps.gov/brca/index.htm"
                        },
                        new
                        {
                            ParkId = 19,
                            Name = "Canyonlands National Park",
                            State = "Utah",
                            Type = "national",
                            Website = "https://www.nps.gov/cany/index.htm"
                        },
                        new
                        {
                            ParkId = 20,
                            Name = "Capiton Reef National Park",
                            State = "Nevada",
                            Type = "national",
                            Website = "https://www.nps.gov/care/index.htm"
                        },
                        new
                        {
                            ParkId = 21,
                            Name = "Zion National Park",
                            State = "Nevada",
                            Type = "national",
                            Website = "https://www.nps.gov/zion/index.htm"
                        },
                        new
                        {
                            ParkId = 22,
                            Name = "Great Basin National Park",
                            State = "Nevada",
                            Type = "national",
                            Website = "https://www.nps.gov/grba/index.htm"
                        },
                        new
                        {
                            ParkId = 23,
                            Name = "Great Basin National Park",
                            State = "Nevada",
                            Type = "national",
                            Website = "https://www.nps.gov/grba/index.htm"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
